const heroNames = [
    "Aethelfirth",
    "Archbishop",
    "Archer of the Eyes",
    "Bad Neighbor",
    "Belisarius",
    "Charlemagne",
    "Charles Martel",
    "Constable Richemont",
    "Duke D'Alençon",
    "El Cid",
    "Emperor in a Barrel",
    "Erik the Red",
    "Frankish Paladin",
    "Friar Tuck",
    "Gawain",
    "Genghis Khan",
    "God's Own Sling",
    "Guy Josselyne",
    "Harold Haardraade",
    "Hrolf the Ganger",
    "Hunting Wolf",
    "Jean Bureau",
    "Jean de Lorrain",
    "Joan of Arc",
    "Joan the Maid",
    "King Arthur",
    "Kitabatake",
    "Kushluk",
    "La Hire",
    "Lancelot",
    "Lord de Graville",
    "Master of the Templar",
    "Minamoto",
    "Mordred",
    "Ornlu the Wolf",
    "Reynald de Chatillon",
    "Richard the Lionheart",
    "Robin Hood",
    "Roland",
    "Saboteur",
    "Shah",
    "Sheriff of Nottingham",
    "Siegfried",
    "Sieur Bertrand",
    "Sieur de Metz",
    "Sir John Fastolf",
    "Subotai",
    "Tamerlane",
    "The Black Prince",
    "Theodoric the Goth",
    "William Wallace",
    "Admiral Yi Sun-Shin",
    "Alexander Nevski",
    "Attila the Hun",
    "Bleda the Hun",
    "El Cid Campeador",
    "Harald Hardrada",
    "Henry V",
    "Imam",
    "King Alfonso",
    "King Sancho",
    "Nobunaga",
    "Pope Leo I",
    "Scythian Scout",
    "Scythian Wild Woman",
    "William the Conqueror",
    "Chand Bhai",
    "Cuauhtemoc",
    "Francesco Sforza",
    "Francisco de Orellana",
    "Frederick Barbarossa",
    "Gonzalo Pizarro",
    "Jarl",
    "Khosrau",
    "Osman",
    "Prithvi",
    "Prithviraj",
    "Saladin",
    "Sanyogita",
    "Sogdian Cataphract",
    "Vlad Dracula",
    "Abraha Elephant",
    "Babur",
    "Dagnajan",
    "Gidajan",
    "Guglielmo Embriaco",
    "Henry II",
    "Huayna Capac",
    "Itzcoatl",
    "Little John",
    "Miklos Toldi",
    "Musa ibn Nusayr",
    "Mustafa Pasha",
    "Pacal II",
    "Pachacuti",
    "Princess Yodit",
    "Richard de Clare",
    "Su Dingfang",
    "Sumanguru",
    "Sundjata",
    "Tariq ibn Ziyad",
    "Yekuno Amlak",
    "Yodit",
    "Zawisza the Black",
    "Bayinnaung",
    "Bui Bi",
    "Dinh Le",
    "Envoy",
    "Gajah Mada",
    "Jayanegara",
    "Jayaviravarman",
    "Le Lai",
    "Le Loi",
    "Le Trien",
    "Luu Nhan Chu",
    "Raden Wijaya",
    "Sunda Royal Fighter",
    "Suryavarman I",
    "Tabinshwehti",
    "Udayadityavarman I",
    "Wang Tong",
    "Alaric the Goth",
    "Ataulf",
    "Cuman Chief",
    "Cusi Yupanqui",
    "Girgen Khan",
    "Henry the Lion",
    "Ivaylo",
    "King Bela IV",
    "Kotyan Khan",
    "Leif Erikson",
    "Mounted Samurai",
    "Sosso Guard",
    "The Middlebrook",
    "Tokhtamysh Khan",
    "Tsar Konstantin",
    "Topa Yupanqui",
    "Urus Khan",
    "Vasco da Gama",
    "Vytautas the Great",
    "Bernard d'Armagnac",
    "Bohemond",
    "Dafydd ap Gruffydd",
    "Edward Longshanks",
    "Gilbert de Clare",
    "Jacqueline of Hainaut",
    "John the Fearless",
    "Llywelyn ap Gruffydd",
    "Philip the Good",
    "Robert Guiscard",
    "Roger Bosso",
    "Algirdas",
    "Dmitry of Moscow",
    "Emperor Sigismund",
    "Jadwiga",
    "Jan Zizka",
    "Jogaila",
    "Kestutis",
    "Mikhail of Tver",
    "Ulrich von Jungingen",
    "Young Jadwiga",
    "Amoghavarsha",
    "General Araiyan",
    "Ibrahim Lodi",
    "Mihira Bhoja",
    "Qutlugh",
    "Rajendra Chola",
    "Shaybani Khan",
    "Young Babur",
];


export default function defaultNickname(id: string) {
    const charSum = id.split('').reduce((sum, letter) => sum + letter.charCodeAt(0), 0);
    return heroNames[charSum % heroNames.length];
}
