const heroNames = [
    'Gonzalo Pizarro',
    'King Bela IV',
    'John the Fearless',
    'Philip the Good',
    'Master of the Templar',
    'Sundjata',
    'Le Loi',
    'Ivaylo',
    'Warwolf',
    'Edward Longshanks',
    'Jacqueline of Hainaut',
    'Admiral Yi Sun-shin',
    'Little John',
    'Pope Leo I',
    'Harald Hardraade',
    'Cobra Car',
    'Kotyan Khan',
    'King Sancho',
    'William The Conqueror',
    'Alaric The Goth',
    'Joan The Maid',
    'Charles Martel',
    'Saladin',
    'Charlemagne',
    'Friar Tuck',
    'Henry The Lion',
    'Princess Yodit',
    'Emperor in a Barrel',
    'Leif Erikson',
    'Sheriff of Nottingham',
    'Bad Neighbor',
    'Vlad Dracula',
    'Subotai',
    'La Hire',
    'Willy Wallace',
    'Ornlu The Wolf',
    'King Alfonso',
    'Erik The Red',
    'Hrolf The Ganger',
    'Attila The Hun',
    'Bleda The Hun',
    'Nobunaga',
    'Robin Hood',
    'Joan Of Arc',
    'Gods Own Sling',
    'Genghis Khan',
    'Tamerlane',
    'El Cid',
];


export default function defaultNickname(id: string) {
    const charSum = id.split('').reduce((sum, letter) => sum + letter.charCodeAt(0), 0);
    return heroNames[charSum % heroNames.length];
}
