name: aoe-ai

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "8345:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
