CREATE TABLE tree (
  id SERIAL PRIMARY KEY,
  tree JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE game_result (
  id SERIAL PRIMARY KEY,
  player1_tree_id INTEGER NOT NULL REFERENCES tree(id),
  player2_tree_id INTEGER NOT NULL REFERENCES tree(id),
  player1_hp INTEGER NOT NULL,
  player2_hp INTEGER NOT NULL,
  ticks INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
