import { createRef, useEffect } from "react";
import { circle } from "../../common/drawing/shapes";
import screenManager from "../../common/drawing/screenManager";
import LineFormation from "../../common/units/formations/types/LineFormation";
import { UnitInstance } from "../../types";
import { Vector2 } from "three/src/math/Vector2";
import Unit from "../../common/units/Unit";

export default function FormationDebugging() {
  const ref = createRef<HTMLCanvasElement>();

  useEffect(() => {
    const canvas = ref.current;
    const ctx = canvas.getContext("2d");

    canvas.width = window.innerWidth * screenManager.getCanvasScale();
    canvas.height = (window.innerHeight - screenManager.getTopOffset()) * screenManager.getCanvasScale();

    const line = new LineFormation();
    const positions = line.form(units, new Vector2(500, 600));
    // line.form();

    positions.map((position, i) => {
      const unit = units[i];
      if (unit.unitType == Unit.Archer) {
        circle(ctx, position, 5, "green");
      }
      if (unit.unitType == Unit.Mangonel) {
        circle(ctx, position, 5, "red");
      }
      if (unit.unitType == Unit.Monk) {
        circle(ctx, position, 5, "blue");
      }
    });
  }, []);

  return (
    <canvas
      style={{ width: "100vw", height: "calc(100vh - 53px)", display: "block", backgroundColor: "black" }}
      ref={ref}
    />
  );
}

const units: Array<UnitInstance> = [
  {
    id: 0,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 1,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 50,
  },
  {
    id: 1,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 2,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 2,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 2,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 3,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 4,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 5,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 6,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 7,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 8,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 9,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 10,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 11,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 12,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 13,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 14,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 15,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 16,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 17,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 18,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 19,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 20,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 21,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 22,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 23,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 24,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 25,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 26,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
  {
    id: 27,
    position: { x: 1104, y: 912 } as Vector2,
    waypoints: [],
    formation: 0,
    clickedWaypoints: [],
    movingDirection: null,
    reloadsAt: 0,
    ownedByPlayer: 1,
    unitType: 0,
    unitState: 0,
    unitStateStartedAt: 60,
    direction: 4,
    hitPoints: 30,
  },
];
