# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

#db:
#    type: mariadb:10.4
#    disk: 1024

dmount:
  type: network-storage:2.0
  disk: 256
